### ISSUE TITLE
运行 webTest 报错

### ISSUE THREAD

**Issue by mvn86** [qtacore/QT4iDemoProj#2]
环境: 
- mac 10.14.2
- qta 版本 5.4.10
- qt4i 版本  3.4.2
- qt4w版本2.0.45
- python 2.7.10
- iOS 12.1.2 
- iphone 6 

被测app 为demo app 

 ### demo 运行webTest 出现的问题如下:

#### 执行方式
```
python manage.py runscript demotest/webtest.py
```
#### 控制台log
``` 
CRITICAL: run_test执行失败
Traceback (most recent call last):
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/testbase/testcase.py", line 707, in _thread_run
    getattr(self._testcase, it)()
  File "demotest/webtest.py", line 28, in run_test
    page = DemoPage(webwin.webview) #------------------------------------# 初始化webpage
  File "/Users/xxxx/github/QT4iDemoProj/demolib/native/webwin.py", line 25, in webview
    return self.Controls['webview']
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/icontrols.py", line 98, in __getitem__
    return cls(**params)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/web.py", line 57, in __init__
    self.page_id = self._init_page_id()
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/web.py", line 68, in _init_page_id
    raise RuntimeError('Failed to init page id reason: %s'%err)
RuntimeError: Failed to init page id reason: Traceback (most recent call last):
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/web.py", line 64, in _init_page_id
    return self._driver.web.get_page_id(self.bundle_id, self.title, self.url_key)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 189, in __request
    raise DriverApiError(response['error']['message'])
DriverApiError: Traceback (most recent call last):
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 497, in _marshaled_dispatch
    response = endpoint._dispatch(method, params)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 93, in _dispatch
    return m(*params)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 70, in __call__
    return self.method.__get__(self.instance, self.owner)(*args, **kwargs)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/web.py", line 52, in get_page_id
    return WebInspector.WKRDP[ub].request_current_page_id(title, url)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 238, in request_current_page_id
    self.send_webkit_message(request)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 317, in send_webkit_message
    self.send(tmp_data)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 122, in send
    sent = self._sock.send(data[total:])
error: [Errno 32] Broken pipe
```
#### webTest log
```log
[2019-01-24 14:44:25,807][pid:48142][tid:123145392775168][ERROR] web.get_page_id >>> {'message': 'Traceback (most recent call last):\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 497, in _marshaled_dispatch\n    response = endpoint._dispatch(method, params)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 93, in _dispatch\n    return m(*params)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 70, in __call__\n    return self.method.__get__(self.instance, self.owner)(*args, **kwargs)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/web.py", line 52, in get_page_id\n    return WebInspector.WKRDP[ub].request_current_page_id(title, url)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 238, in request_current_page_id\n    self.send_webkit_message(request)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 317, in send_webkit_message\n    self.send(tmp_data)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 122, in send\n    sent = self._sock.send(data[total:])\nerror: [Errno 32] Broken pipe\n', 'code': -12306}
[2019-01-24 14:44:25,807][pid:48142][tid:123145392775168][ERROR] {'message': 'Traceback (most recent call last):\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 497, in _marshaled_dispatch\n    response = endpoint._dispatch(method, params)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 93, in _dispatch\n    return m(*params)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 70, in __call__\n    return self.method.__get__(self.instance, self.owner)(*args, **kwargs)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/web.py", line 52, in get_page_id\n    return WebInspector.WKRDP[ub].request_current_page_id(title, url)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 238, in request_current_page_id\n    self.send_webkit_message(request)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 317, in send_webkit_message\n    self.send(tmp_data)\n  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 122, in send\n    sent = self._sock.send(data[total:])\nerror: [Errno 32] Broken pipe\n', 'code': -12306}
Traceback (most recent call last):
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 497, in _marshaled_dispatch
    response = endpoint._dispatch(method, params)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 93, in _dispatch
    return m(*params)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/rpc.py", line 70, in __call__
    return self.method.__get__(self.instance, self.owner)(*args, **kwargs)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/web.py", line 52, in get_page_id
    return WebInspector.WKRDP[ub].request_current_page_id(title, url)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 238, in request_current_page_id
    self.send_webkit_message(request)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 317, in send_webkit_message
    self.send(tmp_data)
  File "/Users/xxxx/Library/Python/2.7/lib/python/site-packages/qt4i/driver/web/wkrdp.py", line 122, in send
    sent = self._sock.send(data[total:])
```

**Comment by hellertang** [comment]
打开手机通用 =》Safari浏览器 =》 高级 =》，把javascript和Web检查器都打开~
然后再跑下demo试一下~
